font_family Liberation Mono
font_size 10
text_composition_strategy legacy

scrollback_lines 10000
scrollback_pager_history_size 100

copy_on_select clipboard
strip_trailing_spaces always

enable_audio_bell yes
bell_on_tab "*"

remember_window_size  no
placement_strategy center
resize_in_steps yes

window_border_width 4pt
draw_minimal_borders no
active_border_color #008800
inactive_border_color #cccccc
bell_border_color #aa0000

tab_bar_edge top
tab_bar_style separator
tab_bar_align center
tab_separator " || "

active_tab_foreground   #FFF
active_tab_background   #000
active_tab_font_style   bold
inactive_tab_foreground #000
inactive_tab_background #FFF
inactive_tab_font_style normal

foreground #000
background #FFF
selection_foreground #FFF
selection_background #000

color0  #000000
color1  #cd0000
color2  #00cd00
color3  #cdcd00
color4  #0000ee
color5  #cd00cd
color6  #00cdcd
color7  #e5e5e5

color8  #7f7f7f
color9  #ff0000
color10 #00ff00
color11 #ffff00
color12 #5c5cff
color13 #ff00ff
color14 #00ffff
color15 #ffffff

term xterm-256color

# KEYBINDS
clear_all_shortcuts yes
map ctrl+shift+r load_config_file

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map opt+page_up scroll_page_up
map opt+page_down scroll_page_down

map opt+g show_last_command_output
map opt+s show_scrollback

map opt+enter new_window
map opt+h neighboring_window left
map opt+j neighboring_window bottom
map opt+k neighboring_window top
map opt+l neighboring_window right
map opt+o next_layout
map opt+z toggle_layout stack

map opt+t new_tab
map opt+n next_tab
map opt+p previous_tab
map opt+x close_tab
map opt++ move_tab_forward
map opt+- move_tab_forward

map opt+. set_tab_title

map opt+1 goto_tab 1
map opt+2 goto_tab 2
map opt+3 goto_tab 3
map opt+4 goto_tab 4
map opt+5 goto_tab 5
map opt+6 goto_tab 6
map opt+7 goto_tab 7
map opt+8 goto_tab 8
map opt+9 goto_tab 9

map ctrl+plus change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
