[keybindings]
"b" = "next"
"c" = "playpause"
"r" = "repeat"
"s" = "shuffle"
"g" = "move top"
"G" = "move bottom"

[theme]
secondary = "black"
title = "black"
playing = "green"
playing_selected = "green"
playing_bg = "white"
highlight = "white"
highlight_bg = "black"
error = "black"
error_bg = "green"
statusbar = "white"
statusbar_progress = "black"
statusbar_bg = "black"
cmdline = "black"
cmdline_bg = "white"
search_match = "green"

